name: base
channels:
  - anaconda
  - https://repo.anaconda.com/pkgs/free
  - conda-forge
  - defaults
dependencies:
  - _ipyw_jlab_nb_ext_conf=0.1.0=py36he6757f0_0
  - _nb_ext_conf=0.4.0=py36_1
  - alabaster=0.7.12=py_0
  - altair=2.1.0=py_0
  - anaconda-client=1.7.2=py_0
  - anaconda-navigator=1.8.7=py36_0
  - arrow-cpp=0.14.1=py36h5c295ed_4
  - asn1crypto=0.24.0=py36_1003
  - astroid=2.3.1=py36_0
  - atomicwrites=1.3.0=py_0
  - attrs=19.1.0=py_0
  - babel=2.7.0=py_0
  - backcall=0.1.0=py_0
  - beautifulsoup4=4.8.0=py36_0
  - blas=1.0=mkl
  - bleach=3.1.0=py_0
  - bokeh=1.3.4=py36_0
  - boost-cpp=1.70.0=h6a4c333_2
  - brotli=1.0.7=he025d50_1000
  - bzip2=1.0.8=hfa6e2cd_1
  - c-ares=1.15.0=h2fa13f4_1001
  - ca-certificates=2019.11.28=hecc5488_0
  - certifi=2019.11.28=py36_0
  - cffi=1.12.3=py36hb32ad35_0
  - chardet=3.0.4=py36_1003
  - click=7.0=py_0
  - cloudpickle=1.2.2=py_0
  - clyent=1.2.2=py_1
  - colorama=0.4.1=py_0
  - conda=4.8.0=py36_1
  - conda-build=3.10.5=py36_0
  - conda-package-handling=1.6.0=py36h2fa13f4_0
  - conda-verify=3.1.1=py36_1000
  - console_shortcut=0.1.1=h6bb2dd7_3
  - cryptography=2.7=py36hb32ad35_0
  - cycler=0.10.0=py_1
  - cytoolz=0.10.0=py36hfa6e2cd_0
  - dask=2.3.0=py_0
  - dask-core=2.3.0=py_0
  - decorator=4.4.0=py_0
  - defusedxml=0.6.0=py_0
  - distributed=2.5.1=py_0
  - docutils=0.15.2=py36_0
  - double-conversion=3.1.5=h6538335_1
  - entrypoints=0.3=py36_1000
  - fastparquet=0.1.5=py36_0
  - filelock=3.0.10=py_0
  - freetype=2.10.0=h563cfd7_1
  - fsspec=0.5.1=py_0
  - future=0.17.1=py36_1000
  - gflags=2.2.2=he025d50_1001
  - glob2=0.7=py_0
  - glog=0.4.0=he025d50_1
  - grpc-cpp=1.23.0=h4d7d3fa_0
  - heapdict=1.0.1=py_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=64.2=he025d50_1
  - idna=2.8=py36_1000
  - imagesize=1.1.0=py_0
  - importlib_metadata=0.23=py36_0
  - intel-openmp=2019.4=245
  - ipykernel=5.1.1=py36h39e3cac_0
  - ipython=7.8.0=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=py_0
  - isort=4.3.21=py36_0
  - jedi=0.15.1=py36_0
  - jinja2=2.10.1=py_0
  - joblib=0.14.0=py_0
  - jpeg=9c=hfa6e2cd_1001
  - json5=0.8.5=py_0
  - jsonschema=3.0.2=py36_0
  - jupyter=1.0.0=py_2
  - jupyter_client=5.3.3=py36_1
  - jupyter_console=6.0.0=py_0
  - jupyter_core=4.4.0=py_0
  - jupyterlab=1.1.4=py_0
  - jupyterlab_server=1.0.6=py_0
  - keyring=19.2.0=py36_0
  - kiwisolver=1.1.0=py36he980bc4_0
  - lazy-object-proxy=1.4.2=py36hfa6e2cd_0
  - libblas=3.8.0=12_mkl
  - libcblas=3.8.0=12_mkl
  - libiconv=1.15=hfa6e2cd_1005
  - liblapack=3.8.0=12_mkl
  - libpng=1.6.37=h7602738_0
  - libprotobuf=3.8.0=h1a1b453_0
  - libsodium=1.0.17=h2fa13f4_0
  - libtiff=4.0.10=h6512ee2_1003
  - libxml2=2.9.9=h9ce36c8_5
  - libxslt=1.1.33=heafd4d3_0
  - llvmlite=0.29.0=py36hed17590_1
  - locket=0.2.0=py_2
  - lxml=4.4.1=py36heafd4d3_0
  - lz4-c=1.8.3=he025d50_1001
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=1.1.1=py36hfa6e2cd_0
  - matplotlib=3.1.1=py36_1
  - matplotlib-base=3.1.1=py36h2852a4a_1
  - mccabe=0.6.1=py_1
  - menuinst=1.4.16=py36_0
  - mistune=0.8.4=py36hfa6e2cd_1000
  - mkl=2019.4=245
  - mkl-service=2.3.0=py36hfa6e2cd_0
  - more-itertools=7.2.0=py_0
  - msgpack-python=0.6.2=py36he980bc4_0
  - msys2-conda-epoch=20160418=1
  - navigator-updater=0.2.1=py36_0
  - nb_anacondacloud=1.4.0=py36_1
  - nb_conda=2.2.1=py36_2
  - nb_conda_kernels=2.1.0=py36_0
  - nbconvert=5.6.0=py36_1
  - nbformat=4.4.0=py_1
  - nbpresent=3.0.2=py36_0
  - notebook=5.5.0=py36_0
  - numba=0.45.1=py36hf9181ef_0
  - numpy=1.17.2=py36hc71023c_0
  - numpydoc=0.9.1=py_0
  - olefile=0.46=py_0
  - openssl=1.1.1d=hfa6e2cd_0
  - packaging=19.2=py_0
  - pandas=0.24.2=py36he350917_0
  - pandoc=2.7.3=0
  - pandocfilters=1.4.2=py_1
  - parquet-cpp=1.5.1=2
  - parso=0.5.1=py_0
  - partd=1.0.0=py_0
  - patsy=0.5.1=py_0
  - pickleshare=0.7.5=py36_1000
  - pillow=6.1.0=py36h643dfcc_1
  - pkginfo=1.5.0.1=py_0
  - pluggy=0.12.0=py_0
  - prompt_toolkit=2.0.9=py_0
  - psutil=5.6.3=py36hfa6e2cd_0
  - py=1.8.0=py_0
  - pyarrow=0.14.1=py36h803c963_0
  - pycodestyle=2.5.0=py_0
  - pycosat=0.6.3=py36hfa6e2cd_1001
  - pycparser=2.19=py36_1
  - pyflakes=2.1.1=py_0
  - pygments=2.4.2=py_0
  - pylint=2.4.2=py36_0
  - pyopenssl=19.0.0=py36_0
  - pyparsing=2.4.2=py_0
  - pyqt=5.9.2=py36h6538335_4
  - pyrsistent=0.15.4=py36hfa6e2cd_0
  - pysocks=1.7.1=py36_0
  - pytest=5.3.4=py36_0
  - python=3.6.5=h0c2934d_0
  - python-dateutil=2.8.0=py_0
  - pytz=2019.2=py_0
  - pywin32=224=py36hfa6e2cd_1000
  - pywin32-ctypes=0.2.0=py36_1000
  - pywinpty=0.5.5=py36_1000
  - pyyaml=5.1.2=py36hfa6e2cd_0
  - pyzmq=18.1.0=py36h16f9016_0
  - qt=5.9.7=h506e8af_3
  - qtawesome=0.6.0=py_0
  - qtconsole=4.5.5=py_0
  - qtpy=1.9.0=py_0
  - re2=2019.08.01=vc14h6538335_0
  - requests=2.22.0=py36_1
  - rope=0.14.0=py_0
  - ruamel_yaml=0.15.71=py36hfa6e2cd_1000
  - scikit-learn=0.21.3=py36h7208079_0
  - scipy=1.3.1=py36h29ff71c_0
  - seaborn=0.9.0=py36_0
  - selenium=3.141.0=py36hfa6e2cd_1000
  - send2trash=1.5.0=py_0
  - setuptools=41.2.0=py36_0
  - sip=4.19.8=py36h6538335_1000
  - six=1.12.0=py36_1000
  - snappy=1.1.7=h6538335_1002
  - snowballstemmer=1.9.1=py_0
  - sortedcontainers=2.1.0=py_0
  - soupsieve=1.9.4=py36_0
  - sphinx=2.2.0=py_0
  - sphinxcontrib-applehelp=1.0.1=py_0
  - sphinxcontrib-devhelp=1.0.1=py_0
  - sphinxcontrib-htmlhelp=1.0.2=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.2=py_0
  - sphinxcontrib-serializinghtml=1.1.3=py_0
  - spyder=3.3.4=py36_1
  - spyder-kernels=0.5.2=py36_0
  - sqlite=3.29.0=hfa6e2cd_1
  - statsmodels=0.10.1=py36hfa6e2cd_0
  - tbb=2019.8=he980bc4_0
  - tblib=1.4.0=py_0
  - terminado=0.8.2=py36_0
  - testpath=0.4.2=py_1001
  - thrift=0.11.0=py36h6538335_1001
  - thrift-cpp=0.12.0=hd042d19_1004
  - tk=8.6.9=hfa6e2cd_1003
  - toolz=0.10.0=py_0
  - tornado=6.0.3=py36hfa6e2cd_0
  - tqdm=4.36.1=py_0
  - traitlets=4.3.2=py36_1000
  - typed-ast=1.4.0=py36hfa6e2cd_0
  - typing=3.6.4=py36_0
  - uriparser=0.9.3=he025d50_1
  - urllib3=1.25.6=py36_0
  - vc=14.1=h21ff451_3
  - vega=1.3.0=py36_0
  - vega_datasets=0.5.0=py_0
  - vs2015_runtime=15.5.2=3
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - wheel=0.33.6=py36_0
  - widgetsnbextension=3.5.1=py36_0
  - win_inet_pton=1.1.0=py36_0
  - wincertstore=0.2=py36_1002
  - winpty=0.4.3=4
  - wrapt=1.11.2=py36hfa6e2cd_0
  - xlrd=1.2.0=py_0
  - xz=5.2.4=h2fa13f4_1001
  - yaml=0.1.7=hfa6e2cd_1001
  - zeromq=4.3.2=h6538335_2
  - zict=1.0.0=py_0
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h2fa13f4_1006
  - zstd=1.4.0=hd8a0e53_0
  - pip:
    - eia-python==1.22
    - pip==18.1
    - pypdf2==1.26.0
prefix: C:\Users\cmcmilla\AppData\Local\Continuum\anaconda3

